# Generated by Django 5.0.14 on 2026-07-17 06:10

import api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveIntegrationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_masked", models.CharField(max_length=30)),
                ("check_http_status", models.IntegerField(blank=True, null=True)),
                ("exists", models.BooleanField(null=True)),
                ("send_http_status", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("provider_state", models.CharField(blank=True, max_length=100)),
                ("response_summary", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_hash", models.CharField(max_length=64, unique=True)),
                ("event_id", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("signature_valid", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                (
                    "processing_state",
                    models.CharField(default="pending", max_length=20),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("body_snapshot", models.TextField()),
                ("selected_phone_column", models.CharField(max_length=255)),
                ("selected_recipient_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validating", "Validating"),
                            ("checking", "Checking"),
                            ("ready", "Ready"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "missing_value_policy",
                    models.CharField(default="empty", max_length=20),
                ),
                (
                    "missing_value_fallback",
                    models.CharField(blank=True, max_length=255),
                ),
                ("allow_duplicates", models.BooleanField(default=False)),
                ("allow_unknown", models.BooleanField(default=False)),
                ("opt_in_confirmed", models.BooleanField(default=False)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("queued_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("read_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("send_config_snapshot", models.JSONField(default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportedRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_row_number", models.PositiveIntegerField()),
                ("row_data", models.JSONField(default=dict)),
                ("selected", models.BooleanField(default=True)),
                ("phone_source_column", models.CharField(blank=True, max_length=255)),
                ("phone_original", models.CharField(blank=True, max_length=255)),
                ("phone_normalized", models.CharField(blank=True, max_length=20)),
                (
                    "phone_validation_status",
                    models.CharField(
                        choices=[
                            ("unchecked", "Unchecked"),
                            ("valid", "Valid"),
                            ("warning", "Warning"),
                            ("invalid", "Invalid"),
                            ("blank", "Blank"),
                        ],
                        default="unchecked",
                        max_length=20,
                    ),
                ),
                ("validation_error_code", models.CharField(blank=True, max_length=50)),
                (
                    "validation_error_message",
                    models.CharField(blank=True, max_length=255),
                ),
                ("auto_corrected", models.BooleanField(default=False)),
                (
                    "whatsapp_state",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("checking", "Checking"),
                            ("exists", "Exists"),
                            ("not_exists", "Not on WhatsApp"),
                            ("error", "Error"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("whatsapp_checked_at", models.DateTimeField(blank=True, null=True)),
                ("suppressed", models.BooleanField(default=False)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="api.importedrecipient",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rendered_message", models.TextField(blank=True)),
                ("normalized_phone", models.CharField(blank=True, max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("invalid", "Invalid"),
                            ("skipped", "Skipped"),
                            ("cancelled", "Cancelled"),
                            ("queued", "Queued"),
                            ("accepted", "Provider accepted"),
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("played", "Played"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("skip_reason", models.CharField(blank=True, max_length=255)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("provider_jid", models.CharField(blank=True, max_length=255)),
                ("provider_status_code", models.IntegerField(blank=True, null=True)),
                ("provider_status_text", models.CharField(blank=True, max_length=100)),
                ("last_provider_payload", models.JSONField(default=dict)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_recipients",
                        to="api.campaign",
                    ),
                ),
                (
                    "imported_recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_entries",
                        to="api.importedrecipient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField()),
                ("request_payload", models.JSONField(default=dict)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("provider_response", models.JSONField(default=dict)),
                ("error_category", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "campaign_recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="api.campaignrecipient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("detected_placeholders", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.messagetemplate",
            ),
        ),
        migrations.CreateModel(
            name="SuppressedRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("normalized_phone", models.CharField(max_length=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(blank=True, max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_file",
                    models.FileField(
                        upload_to=api.models.user_upload,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["xlsx", "xls", "csv"]
                            )
                        ],
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("checksum", models.CharField(max_length=64)),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                ("header_row_number", models.PositiveIntegerField(default=1)),
                ("detected_columns", models.JSONField(default=list)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("selected_phone_column", models.CharField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="importedrecipient",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="api.uploadeddataset",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="api.uploadeddataset",
            ),
        ),
        migrations.CreateModel(
            name="UploadedMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_file", models.FileField(upload_to=api.models.user_upload)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("media_type", models.CharField(max_length=20)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(max_length=64)),
                ("provider_public_url", models.URLField(blank=True, max_length=1000)),
                (
                    "provider_url_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("upload_error", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="default_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.uploadedmedia",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.uploadedmedia",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignrecipient",
            constraint=models.UniqueConstraint(
                fields=("campaign", "imported_recipient"),
                name="unique_campaign_recipient",
            ),
        ),
        migrations.AddConstraint(
            model_name="messageattempt",
            constraint=models.UniqueConstraint(
                fields=("campaign_recipient", "attempt_number"),
                name="unique_attempt_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="suppressedrecipient",
            constraint=models.UniqueConstraint(
                fields=("owner", "normalized_phone"), name="unique_owner_suppression"
            ),
        ),
        migrations.AddIndex(
            model_name="importedrecipient",
            index=models.Index(
                fields=["owner", "phone_normalized"],
                name="api_importe_owner_i_566ef1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importedrecipient",
            index=models.Index(
                fields=["dataset", "selected"], name="api_importe_dataset_c44ee1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importedrecipient",
            constraint=models.UniqueConstraint(
                fields=("dataset", "original_row_number"), name="unique_dataset_row"
            ),
        ),
    ]
